# Site settings
name: Anh Bernhardt
title: Anh Bernhardt | Portfolio
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://ahbernhardt.github.io/portfolio-2020/
baseurl: ''
email: anhbernhardt@gmail.com
cover: https://ahbernhardt.github.io/portfolio-2020/img/og.png
logo: https://ahbernhardt.github.io/portfolio-2020/img/logo/favicon-32x32.png
resume: https://ahbernhardt.github.io/portfolio-2020/resume.pdf
social:
  - title: linkedin
    url: https://www.linkedin.com/in/anhbernhardt
  - title: email
    url: mailto:anhbernhardt@gmail.com
  - title: github
    url: https://github.com/ahbernhardt
  - title: instagram
    url: https://instagram.com/ah_bernhardt
  - title: codepen
    url: https://codepen.io/ah_nguyen0208

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

jekyll-minifier:
  uglifier_args:
    harmony: true
