# Site settings
name: Anh Nguyen
title: Anh Nguyen | Portfolio
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://anguyen0208.github.io/v2
baseurl: ''
email: anhbernhardt@gmail.com
cover: https://anguyen0208.github.io/img/og.png
logo: https://anguyen0208.github.io/img/logo/favicon-32x32.png
resume: https://anguyen0208.github.io/resume.pdf
social:
  - title: linkedin
    url: https://www.linkedin.com/in/anhbernhardt
  - title: email
    url: mailto:anhbernhardt@gmail.com
  - title: github
    url: https://github.com/anguyen0208
  - title: instagram
    url: https://instagram.com/ah_nguyen0208
  - title: codepen
    url: http://codepen.io/ah_nguyen0208


# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

jekyll-minifier:
  uglifier_args:
    harmony: true
